#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task
# Add header to the nginx config

sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
